### ISSUE TITLE
Database cannot handle input files with apostrophes

### ISSUE THREAD

**Issue by frogsquire** [Kaan0200/Zoodevio_VideoLibrary#11]
File names aren't sanitized in/out of the database. Will have to add a handler. 

Example from SetLibraryRoot: 
`1 12:00:00 AM', '11/6/2015 6:15:18 PM')insert into files (path, date_added, date_edited) values ('G:\Videos\Gossip Girl\Season 1\Gossip Girl - S1E06 - The Handmaiden's Tale.avi', '1/1/0001 12:00:00 AM', '11/6/2015 6:15:18 PM')System.Data.SQLite.SQLiteException (0x80004005): SQLite error
near "s": syntax error
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteCommand.GetStatement(Int32 index)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   at Zoodevio.DataModel.Database.SimpleInsertQuery(String table, String[] rows, String[] data) in C:\Users\Max Zimon\Documents\GitHubVisualStudio\Zoodevio_VideoLibrary\Zoodevio\DataModel\Database.cs:line 144Files table addition failed:
    G:\Videos\Gossip Girl\Season 1\Gossip Girl - S1E06 - The Handmaiden's Tale.avi`

Note the apostrophe in "Handmaiden's." Other files in this format (video name - episode code - name) add correctly.

**Comment by Kaan0200** [comment]
Oh yeah, this is a problem in SQL.  I've seen this before with people named "O'Malley" or such.

We can add a handle to either sanitize all apostrophes, OR, we can handle them by escaping the apostrophes.  You do this by writing 'Handmaiden''s'  (those are all single apostrophe, the middle 2 are just two singles, twice).

**Comment by frogsquire** [comment]
I assume that if we escape the apostrophes, they'll go into the database with just one, and so will only have to be sanitized going in, not coming out?

If so, that's the way I'll go.

**Comment by Kaan0200** [comment]
Yup, I just tested it.  We will do cleaning application side.
![2015-11-06 21_16_17-db browser for sqlite - d__user files_workspace_zoodevio_videolibrary_zoodevio_d](https://cloud.githubusercontent.com/assets/6645538/11013004/b6266b6c-84cb-11e5-8831-4a5c2b8e67c1.jpg)

**Comment by frogsquire** [comment]
So this method works in the SQLite browser, but it does not work in the code. The exact same query that passes in the DB browser fails when run from inside Zoodevio (I copied and pasted from the debug output below). Investigating.

`insert into files (path, date_added, date_edited) values ('C:\Users\Max Zimon\Videos\goofy''goobers.avi', '11/15/2015 10:50:58 PM', '11/15/2015 10:50:58 PM')Exception thrown: 'System.Data.SQLite.SQLiteException' in System.Data.SQLite.dll
System.Transactions Critical: 0 : <TraceRecord xmlns="http://schemas.microsoft.com/2004/10/E2ETraceEvent/TraceRecord" Severity="Critical"><TraceIdentifier>http://msdn.microsoft.com/TraceCodes/System/ActivityTracing/2004/07/Reliability/Exception/Unhandled</TraceIdentifier><Description>Unhandled exception</Description><AppDomain>Zoodevio.vshost.exe</AppDomain><Exception><ExceptionType>System.Data.SQLite.SQLiteException, System.Data.SQLite, Version=1.0.66.0, Culture=neutral, PublicKeyToken=db937bc2d44ff139</ExceptionType><Message>SQLite error
near "goobers": syntax error</Message><StackTrace>   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String&amp;amp; strRemain)`

**Comment by frogsquire** [comment]
Update: the problem is actually on reading the file with an apostrophe in it. It's getting into the database but crashing the reader when it comes out. Looking into it.
